fn main() {
    // Declares the nine `commands/` app commands and `report_unread` (design.md §2.2.12; Task
    // 1.9) so tauri-build autogenerates their ACL permissions
    // (`allow-<kebab-command>`), the same pattern the `spike/m0-harness`
    // branch validated for `report_unread` (SP3): after a real build, each
    // one appears in `src-tauri/gen/schemas/acl-manifests.json` under
    // `__app-acl__`, and `src-tauri/permissions/autogenerated/<name>.toml`
    // is generated per command. `capabilities/shell.json`'s `permissions`
    // list is checked against this same set of names by
    // `commands::tests::shell_capability_is_scoped_to_shell_and_settings_with_the_expected_permissions`
    // (a build script cannot depend on the crate it builds, so that test —
    // not this file — is what keeps the two lists honest against each
    // other; see `commands/mod.rs`'s `COMMAND_NAMES`).
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_snapshot",
            "add_service",
            "update_service",
            "remove_service",
            "reorder_services",
            "select_service",
            "update_settings",
            "open_settings",
            "reload_service",
            "get_diagnostics",
            // Task 2.1 (design.md §2.2.6): granted only through the runtime
            // per-service capability (Task 2.2), never through shell.json.
            "report_unread",
        ]),
    ))
    .expect("failed to run tauri-build for eluma");
}
